### ISSUE TITLE
Please add volume control

### ISSUE THREAD

**Issue by webxl** [CONNCTED/homebridge-soundtouch#11]
There is a volume characteristic now: https://developer.apple.com/homekit/specification/

**Comment by geertsmichael** [comment]
Yes, I also saw that.  I need to wait until this library updates, so I can make use of the characteristic volume: https://github.com/nfarina/homebridge

**Comment by webxl** [comment]
Thanks. Looks like this is the issue to track: https://github.com/nfarina/homebridge/issues/1326

Doesn't seem like a lot of work but what do I know.

**Comment by Joegratz** [comment]
The "Speaker" accessory is not supported in the iOS 10 Home app. I made a fake speaker with HAP-NodeJS to check. You can pair with it, but then it says "Not Supported. This accessory is not currently supported by the Home app." Maybe in the iOS 11 Home app?

**Comment by geertsmichael** [comment]
You can determine now, to configure the device as a switch or as a speaker. (still not working as speaker, but the code is ready) Check README.md file for instructions. (available as of version 5.0.8)
I will apply any fixes as soon as Apple releases the speaker accessory type in their app.
