### ISSUE TITLE
Switch action activates the incorrect speaker

### ISSUE THREAD

**Issue by jeffvautin** [CONNCTED/homebridge-soundtouch#12]
I have two speakers, labeled "Kitchen" and "Living Room". Things worked well for a long time, but recently both switches in the Home App are activating the Kitchen speaker. Perhaps there was an API change recently?

Thanks for maintaining this plugin!

**Comment by eaglexp** [comment]
How to add multiple Sound Touch speakers into the config.json?  
Thank you.

**Comment by jeffvautin** [comment]
Here's the `accessories` part of my config.json, with multiple speakers:
```
"accessories": [
        {
            "accessory": "SoundTouch",
            "name": "Kitchen Speaker",
            "room": "Kitchen"
        },
        {
            "accessory": "SoundTouch",
            "name": "Living Room Speaker",
            "room": "Living Room"
        }
    ]
```

**Comment by geertsmichael** [comment]
I did verify this and it always controls the correct speaker for me.
Please re-open if it's still occurring.
