### ISSUE TITLE
homebridge-soundtouch V5.0.0

### ISSUE THREAD

**Issue by Nastras** [CONNCTED/homebridge-soundtouch#15]
Hello,

I have just installed the update to version 5.0.0. When starting the Homebridge I get the following message displayed.

HAP Warning: Characteristic 00000025-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000113-0000-1000-8000-0026BB765291. Adding anyway.
Jan 02 05:18:44 server homebridge[25932]: Started Searching...

The speakers continue to work. The mute function does not work.

**Comment by ZookeRooi** [comment]
Hi,

I have the same issue:

I have update too the latest version available of homebridge-soundtouch. I hava also updated my Homebridge to the latest version. When I start Homebridge it gives me the following message:
[Speaker Woonkamer] Initializing SoundTouch accessory...
HAP Warning: Characteristic 00000025-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000113-0000-1000-8000-0026BB765291. Adding anyway.

After that it says in Homekit the the speaker is not a suitbale accessiores and I am not able to control it.

**Comment by geertsmichael** [comment]
Please try out version 5.0.2.
I moved back to the previous HomeKit accessory type which is switch. 
You can also use the type speaker by adding type = speaker to the config file if needed (see readme file).

**Comment by Nastras** [comment]
Thanks for the quick fix. Will test it.

One more question to you, is it possible to include a slider that allows you to select the six presets?

Then the sound touch plugin would be really good because you could set in the trigger synonymous which radio station should start when awakening :-)

**Comment by geertsmichael** [comment]
I just updates the code base and published version 5.0.8.
This version supports a preset slider, can you verify if this works for you?

**Comment by Nastras** [comment]
I test it now give me a moment please.

**Comment by Nastras** [comment]
I just made the update to version 5.0.8

I still get this warning:

Jan 02 21:50:47 server homebridge[24402]: [2018-1-2 21:50:47] [Lautsprecher Kinderzimmer] Initializing SoundTouch accessory...
Jan 02 21:50:47 server homebridge[24402]: HAP Warning: Characteristic 00000025-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000113-0000-1000-8000-0026BB765291. Adding anyway.
Jan 02 21:50:47 server homebridge[24402]: Started Searching...
Jan 02 21:50:47 server homebridge[24402]: [2018-1-2 21:50:47] [Lautsprecher Badezimmer] Initializing SoundTouch accessory...
Jan 02 21:50:47 server homebridge[24402]: HAP Warning: Characteristic 00000025-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000113-0000-1000-8000-0026BB765291. Adding anyway.
Jan 02 21:50:47 server homebridge[24402]: Started Searching...
Jan 02 21:50:47 server homebridge[24402]: [2018-1-2 21:50:47] [Lautsprecher Wohnzimmer] Initializing SoundTouch accessory...
Jan 02 21:50:47 server homebridge[24402]: HAP Warning: Characteristic 00000025-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000113-0000-1000-8000-0026BB765291. Adding anyway.
Jan 02 21:50:47 server homebridge[24402]: Started Searching...
Jan 02 21:50:47 server homebridge[24402]: [2018-1-2 21:50:47] [Lautsprecher Schlafzimmer] Initializing SoundTouch accessory...
Jan 02 21:50:47 server homebridge[24402]: HAP Warning: Characteristic 00000025-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000113-0000-1000-8000-0026BB765291. Adding anyway.
Jan 02 21:50:47 server homebridge[24402]: Started Searching...
Jan 02 21:50:47 server homebridge[24402]: [2018-1-2 21:50:47] [Lautsprecher Garage] Initializing SoundTouch accessory...
Jan 02 21:50:47 server homebridge[24402]: HAP Warning: Characteristic 00000025-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000113-0000-1000-8000-0026BB765291. Adding anyway.
Jan 02 21:50:47 server homebridge[24402]: Started Searching...
Jan 02 21:50:47 server homebridge[24402]: [2018-1-2 21:50:47] [Lautsprecher Kueche] Initializing SoundTouch accessory...
Jan 02 21:50:47 server homebridge[24402]: HAP Warning: Characteristic 00000025-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000113-0000-1000-8000-0026BB765291. Adding anyway.


The slider is not displayed to me either.

I have in the config.json "type": "speaker" added must be added something so that the prest slider is displayed?

**Comment by Nastras** [comment]
This is how the loudspeaker currently looks in my HomeKit app:

![img_0088](https://user-images.githubusercontent.com/27686185/34499733-b0dc5e38-f007-11e7-8512-193b2b12f852.jpg)


I've also looked again if really the right version is installed

![ohne titel](https://user-images.githubusercontent.com/27686185/34499769-db812e0c-f007-11e7-9b97-e015b44b4211.jpeg)

**Comment by Nastras** [comment]
Just tested mute. Unfortunately, nothing happens here when the switch is turned. Sound will continue to be output from the speaker.

**Comment by geertsmichael** [comment]
For the presets, you don’t need to add the type = speaker to the config. 
The mute option for speaker, i still need to implement.

**Comment by Nastras** [comment]
It works, I have removed "speaker" and made a restart now the slider is displayed.

Really great, I've been waiting for this feature for a long time.

Thank you so much! You my hero of the day .-)

I hope the plugin is still maintained by you and updated on demand.

Thanks again.

**Comment by geertsmichael** [comment]
I will keep improving and maintaining this. Any new requests for improvements can be logged.

**Comment by ZookeRooi** [comment]
Thanks! It does work again but I do not find a slider in my HomeKit. How do I find/activate that then? In my HomeKit it just appears as a switch.

**Comment by Nastras** [comment]
Try changing the name of a speaker in the config.json. Then restart your HomeBridge and see if the slider is displayed. If so, you can change the names again. That's how it worked for me.

**Comment by ZookeRooi** [comment]
I have tried it but without succes. It keeps appearing as a switch. Can it be that the type speaker is nog yet supported in the dutch version of Homekit: Woning ?

**Comment by Nastras** [comment]
You still need to set your devices without the Speaker line in the config.json to get no error message and get the new preset function displayed.

**Comment by ZookeRooi** [comment]
I am doing something stupid I presume but I just don't see it. This is how I have added the presets to my config.json:
"accessories": [{
		"accessory": "SoundTouch-Preset",
		"name": "Kerst",
		"room": "Woonkamer",
		"preset": "1"
	}, {
		"accessory": "SoundTouch-Preset",
		"name": "Chill",
		"room": "Woonkamer",
		"preset": "3"
And this is what I get in Woning iOs 11.2.1:

![image-1](https://user-images.githubusercontent.com/25376678/34537589-47d28f8a-f0c9-11e7-8b1b-ac43b3f22434.jpg)

**Comment by Nastras** [comment]
Try it without preset line and the accessory is SoundTouch look @ the example config and the plugin Install ist homebridge-soundtouch and not homebridge-soundtouch-preset or other forks.

Example config:

    "accessories": [
		{
			"accessory": "SoundTouch",
			"name": "Speaker Bathroom",
			"room": "Bathroom"
		}
	],


This is your right config:

{
"accessory": "SoundTouch",
"name": "Kerst",
"room": "Woonkamer"
},

**Comment by ZookeRooi** [comment]
Thanks, that works but that does not give me acces to a slider. That is right?

**Comment by Nastras** [comment]
Now change the name from one speaker in your config and restart your homebridge. Now i hope the slider acces.

After this you can change the name again to the old name.

**Comment by ZookeRooi** [comment]
I tried that but it does not work. Should I be able to change the type to “speaker” and not switch, lamp or ventilator?

**Comment by geertsmichael** [comment]
you only choose between type 'switch' or 'speaker'. I will explain the difference.
Switch: 
- The Homekit app things this is a switch
- Using siri, you can only turn on and off (like a switch)
- Using scenes, you can control volume and preset
- Works in any Homekit app (Apple and third party)

Speaker:
- Apple will support this in the future, but IOS 11 doesn't support the type speaker
- Will be better, so we don't need to fake that the device is a switch for HomekIt
- Apple's official homekit app, doesn't support this, but third party apps do support this type.
- (Mute is not implemented yet)
- Cannot be used to control using siri

**Comment by geertsmichael** [comment]
I finished the implementation of the Speaker type and the mute switch works now.
It's kind of a strange implementation as it actually behaves the same as the on/off switch used in the type switch.
Any feedback is welcome.

**Comment by Nastras** [comment]
Cool!

Is the preset function also available for speaker?

**Comment by geertsmichael** [comment]
As of version 5.2.0 that I just pushed out, yes. :)

**Comment by Nastras** [comment]
I just tested it with the speaker type. Nice the presets are now available.
The mute switch now replaces the on and off function of the old switch.

Personally, I do not think so nice. Do you have no possibility because mute switch with the original function of Bose to occupy and additionally an on and off switch to insert?

Great work what you have done so far

Greeting Nastras

**Comment by Nastras** [comment]
@geertsmichael 

I noticed another mistake with the Mute button.

The function is reversed, if I set the button to Mute the speaker is turned on and if not mute the speaker is off.

Can you fix this?

**Comment by Nastras** [comment]
In addition, the speakers can not be turned off via Siri, i think because the switch is missing with on and off power?

No matter if the device name, service or the whole room is switched off. Siri does not turn off the speakers.
