### ISSUE TITLE
Speaker "not suitable"

### ISSUE THREAD

**Issue by ZookeRooi** [CONNCTED/homebridge-soundtouch#16]
I have update too the latest version available of homebridge-soundtouch. I hava also updated my Homebridge to the latest version. When I start Homebridge it gives me the following message:
 _[Speaker Woonkamer] Initializing SoundTouch accessory...
HAP Warning: Characteristic 00000025-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 00000113-0000-1000-8000-0026BB765291. Adding anyway._

After that it says in Homekit the the speaker is not a suitbale accessiores.

Can anybody help me...?

**Comment by geertsmichael** [comment]
Please try out version 5.0.2.
I moved back to the previous HomeKit accessory type which is switch.
You can also use the type speaker by adding type = speaker to the config file if needed (see readme file).
(this is a duplicate issue)
