### ISSUE TITLE
Multiple Sound Touch Systems

### ISSUE THREAD

**Issue by geberr** [CONNCTED/homebridge-soundtouch#2]
Can anyone share a config file example on how to configure multiple sound touch system on the same network?

Much appreciated!

**Comment by offle** [comment]
Hi, this is working for me

`
    "accessories": [
         {
            "accessory": "SoundTouch",
            "name": "Bose Flur",
            "room": "offleBoseFlur"
         },
         {
            "accessory": "SoundTouch",                                                                                                            
            "name": "Bose Wohnzimmer",                                                                                                            
            "room": "offleBoseCM120"                                                                                                              
},
         {
            "accessory": "SoundTouch",
            "name": "Bose Dusche",
            "room": "offleBoseDusche"
         }


    ]`

**Comment by geertsmichael** [comment]
Correct.
