### ISSUE TITLE
Soundtouch Alarm Clock (Homekit Automation)

### ISSUE THREAD

**Issue by eliransapir** [CONNCTED/homebridge-soundtouch#5]
Hi thank you for putting this together. I would like to use the homekit automation function as a sort of an alarm clock. My question is how can i have it automatically select a predefined preset and volume level when it gets the turn on command?

**Comment by geertsmichael** [comment]
Since version 5.0.8, I added a preset slider. Does this help solving your issue?

**Comment by eliransapir** [comment]
For both Volume & Source Preset? If so then absolutely yes. Thank you.

**Comment by geertsmichael** [comment]
For both volume and presets.
