### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by offle** [CONNCTED/homebridge-soundtouch#6]
Hi!

Thanks for your great work. Is it possible to control the volume in the iOS home app? The devices are shown as a switch with on/off. In the Elgate Eve app I can control the volume. Is this an issue in the Apple Home app or would it be possible to change the type of the devices as a dimmable light?

**Comment by geertsmichael** [comment]
The 'Volume' characteristic is not a supported one by Homekit. Other apps will visualise the volume sliders, but Apple did not apparently. I will try to implement this as a dimmable light. Feel free to fix the code yourself. I will reply on this issue if I can find some time to fix it.

**Comment by buzyvuzy** [comment]
Hi, i'm not a programmer, but i found in code some about Volume.
I understand that Volume is not supported by Siri, But maybe is it possible to turn on the speaker with preconfigured volume? For example  i need 2 scenario 1) 30% of volume (relax mode) and 2) 80% of volume (party mode).

Is it possible to do with your plugin?

**Comment by geertsmichael** [comment]
Yes, that is possible. If you create a scene with the configuration you mention. If enabling the scene using Siri, the Bose Soundtouch speaker will start with the pre-configured volume.

**Comment by buzyvuzy** [comment]
Thanks for your answer.
But it doesn't work in my case.
Could you show example of config code for accessory?

I tried with next
`    "accessories": [
        {
            "accessory": "SoundTouch",
            "name": "Speaker Bathroom",
            "room": "Bathroom",
            "volume": "80"
        }
    ],

And also I tried with

"volume": "80%"
`

So I can turn on the speaker with this code but the volume of sound always the same, which I set last time from the IR remote

**Comment by geertsmichael** [comment]
You just need to set this up as  
{
            "accessory": "SoundTouch",
            "name": "Speaker Bathroom",
            "room": "Bathroom"
        }

Then restart homebridge and go the Apple Home or Homekit app and try to control the Soundtouch from one of these apps. If that is possible, you should be able to create a scene in the app.

**Comment by buzyvuzy** [comment]
Unfortunately, in the HomeKit is only switch On and Off and no any other options.
Maybe I can send you any additional info? To help me to solve that?

**Comment by geertsmichael** [comment]
I am using the homekit app (which is not the official apple app). The homekit app is not free. Other Homekit apps like Insteon+ or Beam or Eve can be used as well. These are free.
